# -*- coding: utf-8 -*-
"""acdt_g31

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F5fm0D95_3CLMpKv3LVVCJCWz4Vwmcv_
"""

import warnings
warnings.filterwarnings("ignore")

import streamlit as st
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import statsmodels.formula.api as smf
from difflib import get_close_matches

st.set_page_config(page_title="ACDT G31 – GERD(2020) → GDP(2023)", layout="wide")

DATA_FILE = "ACDT_final_dataset.csv"

GDP_NAME  = "Real GDP (billion USD, PPP-based, Chain-weighted, 2020 base year)"
GERD_NAME = "Gross Domestic Expenditure on R&D (GERD) (current PPP USD)"

MEDIATOR_NAMES = [
    "Resident Patent Applications",
    "Non-Resident Patent Applications",
    "R&D Researchers per Million People",
    "High-tech Export Share (% of Manufactured Exports)",
    "Business R&D Personnel (FTE)",
]
CONFOUNDER_NAMES = [
    "GDP per Capita",
    "Labor Force Size",
]
MODERATOR_NAMES  = [
    "Government-financed BERD (%)",
    "Business-financed BERD (%)",
]

X_YEAR = 2020
Y_YEAR = 2023  # GDP 및 기타 변수들 이 연도만 사용

@st.cache_data
def read_as_multiindex_v2(path: str, debug: bool = False) -> pd.DataFrame:
    raw, last_err = None, None
    for enc in ("utf-8-sig", "cp949"):
        try:
            raw = pd.read_csv(path, header=None, encoding=enc, engine="python")
            break
        except Exception as e:
            last_err = e
    if raw is None:
        raise RuntimeError(f"CSV read failed: {last_err}")

    if debug:
        st.subheader("🔎 DEBUG: Raw CSV (before parsing)")
        st.write("raw.shape:", raw.shape)
        row0, row1 = raw.iloc[0], raw.iloc[1]
        st.write("row0 (years) — first 30:", row0.astype(str).tolist()[:30])
        st.write("row1 (indicator names) — first 30:", row1.astype(str).tolist()[:30])
        st.dataframe(raw.iloc[:6, :20])
        st.info("⬆️ 원시 헤더 및 일부 데이터 확인 완료, 디버그 모드로 앱 실행 중지")
        st.stop()

    if int(raw.shape[1]) == 1:
        try:
            sample_text = "\n".join(raw.iloc[:min(5, len(raw)), 0].astype(str).tolist())
            found_sep = None
            for s in (",", "\t", ";", "|"):
                if sample_text.find(s) != -1:
                    found_sep = s
                    break
            if found_sep is not None:
                col0 = raw.iloc[:, 0].astype(str)
                raw = col0.str.split(found_sep, expand=True)
        except Exception:
            pass

    years = raw.iloc[0].astype(str).str.strip().values
    names = raw.iloc[1].astype(str).str.strip().values
    df = raw.iloc[2:].copy()
    df.columns = pd.MultiIndex.from_arrays([names, years], names=["Indicator", "Year"])

    def clean_series(s: pd.Series) -> pd.Series:
        s = s.astype(str)
        s = s.str.replace(",", "", regex=False)
        s = s.str.replace(r"[^0-9eE+\-\.]", "", regex=True)
        return pd.to_numeric(s, errors="coerce")

    for j in range(df.shape[1]):
        df.iloc[:, j] = clean_series(df.iloc[:, j])

    try:
        new_cols = []
        for ind, yr in df.columns:
            ystr = str(yr)
            if ystr.replace(".", "", 1).isdigit():
                yv = int(float(ystr))
            else:
                yv = yr
            new_cols.append((ind, yv))
        df.columns = pd.MultiIndex.from_tuples(new_cols, names=["Indicator", "Year"])
    except Exception:
        pass

    if df.columns.duplicated(keep=False).any():
        df = df.T.groupby(level=["Indicator", "Year"]).mean(numeric_only=True).T
        df.index = pd.RangeIndex(len(df))

    return df

def s_at_v2(df_mi: pd.DataFrame, name: str, year) -> pd.Series:
    lvl0 = df_mi.columns.get_level_values(0)
    if name in set(lvl0):
        sub = df_mi.loc[:, name]
        cols = list(sub.columns) if hasattr(sub, "columns") else []
        if year in cols:
            return df_mi.loc[:, (name, year)]
    return pd.Series([np.nan] * len(df_mi), index=df_mi.index)

def build_pair_dataset(df_mi: pd.DataFrame, x_year: int, y_year: int) -> pd.DataFrame:
    out = pd.DataFrame(index=df_mi.index)
    out["GERD"] = s_at_v2(df_mi, GERD_NAME, x_year)
    out["GDP"]  = s_at_v2(df_mi, GDP_NAME,  y_year)
    for v in CONFOUNDER_NAMES + MEDIATOR_NAMES + MODERATOR_NAMES:
        out[v] = s_at_v2(df_mi, v, y_year)
    out["ln_X"] = np.log(out["GERD"].replace({0: np.nan}))
    out["ln_Y"] = np.log(out["GDP"].replace({0: np.nan}))
    out = out.dropna(subset=["ln_X", "ln_Y"]).reset_index(drop=True)
    return out

def run_models(df_reg: pd.DataFrame):
    confs = [c for c in CONFOUNDER_NAMES if c in df_reg.columns]
    meds  = [m for m in MEDIATOR_NAMES  if m in df_reg.columns]
    mods  = [m for m in MODERATOR_NAMES if m in df_reg.columns]

    m1 = smf.ols("ln_Y ~ ln_X", data=df_reg).fit()
    rhs2 = "ln_X" + ((" + " + " + ".join([f'Q(\"{c}\")' for c in confs])) if confs else "")
    m2 = smf.ols(f"ln_Y ~ {rhs2}", data=df_reg).fit()
    rhs3 = rhs2 + ((" + " + " + ".join([f'Q(\"{m}\")' for m in meds])) if meds else "")
    m3 = smf.ols(f"ln_Y ~ {rhs3}", data=df_reg).fit()
    inter = " + ".join([f'ln_X * Q(\"{mo}\")' for mo in mods]) if mods else ""
    rhs4 = rhs3 if not inter else f"{rhs3} + {inter}"
    m4 = smf.ols(f"ln_Y ~ {rhs4}", data=df_reg).fit()

    def pick(mod, key="ln_X"):
        return mod.params.get(key, np.nan), mod.pvalues.get(key, np.nan), mod.rsquared_adj

    rows = []
    for label, mod in [("M1: lnY~lnX", m1), ("M2:+conf", m2), ("M3:+med", m3), ("M4:+mods", m4)]:
        beta, pval, adjr2 = pick(mod, "ln_X")
        rows.append([label, beta, pval, adjr2])
    summary = pd.DataFrame(rows, columns=["Model", "β(ln_X)", "p(ln_X)", "Adj.R²"]).round(4)
    return {"M1": m1, "M2": m2, "M3": m3, "M4": m4}, summary

# ------------ UI START ------------

st.title("📈 GERD(2020) → GDP(2023) – Models 1~4 with Viz & Debug")

with st.sidebar:
    debug_mode = st.checkbox("Debug: 원시 CSV 헤더 출력 후 앱 중단", False)
    st.caption("디버그 모드 켜면 원시 CSV 헤더(row0, row1) 미리 보기 후 앱 중단")

try:
    df_mi = read_as_multiindex_v2(DATA_FILE, debug=debug_mode)
except Exception as e:
    st.error(f"Error loading data: {e}")
    st.stop()

st.success("✅ 데이터셋 로드 및 전처리 완료 (Row0=Year / Row1=Indicator)")

available_names = sorted(set(df_mi.columns.get_level_values(0)))
needed = [GDP_NAME, GERD_NAME] + MEDIATOR_NAMES + CONFOUNDER_NAMES + MODERATOR_NAMES
missing = [n for n in needed if n not in available_names]
if missing:
    st.warning("다음 지표명이 CSV에 없음 (철자/공백/기호 주의)")
    for m in missing:
        sugg = get_close_matches(m, available_names, n=3, cutoff=0.6)
        st.write(f"- `{m}` → 후보: {sugg}")
    st.info("⚠️ 지표명이 정확해야 회귀 데이터가 완성됩니다")

st.header("📊 분포 및 상관")
flat = df_mi.copy()
flat.columns = [f"{a} [{b}]" for a, b in flat.columns]
num_only = flat.select_dtypes(include=np.number)
if not num_only.empty:
    st.write(num_only.describe().T)
    try:
        fig, ax = plt.subplots(figsize=(12, 7))
        sns.heatmap(num_only.corr(), cmap="coolwarm", center=0, ax=ax)
        ax.set_title("상관관계 행렬")
        st.pyplot(fig)
    except Exception:
        st.info("상관 시각화 스킵됨")
else:
    st.info("수치형 데이터가 없습니다")

st.markdown("---")
st.header(f"🧮 GERD({X_YEAR}) → GDP({Y_YEAR}) 단순+다중회귀")

df_reg = build_pair_dataset(df_mi, X_YEAR, Y_YEAR)
if df_reg.empty:
    st.error("회귀에 적합한 데이터 없음 (ln_X, ln_Y)에 NaN 존재")
    st.stop()

st.subheader("회귀 데이터 미리보기")
st.dataframe(df_reg.head())

st.subheader("산점도 (ln GERD vs ln GDP)")
fig, ax = plt.subplots(figsize=(7, 5))
sns.regplot(x="ln_X", y="ln_Y", data=df_reg, scatter_kws={"alpha": 0.6}, ax=ax)
ax.set_xlabel(f"ln GERD ({X_YEAR})")
ax.set_ylabel(f"ln GDP ({Y_YEAR})")
st.pyplot(fig)

models, summary = run_models(df_reg)
st.subheader("회귀 모델 비교표")
st.dataframe(summary)

fig2, ax2 = plt.subplots(figsize=(6, 4))
sns.barplot(x="Model", y="Adj.R²", data=summary, ax=ax2)
ymax = float(summary["Adj.R²"].max()) if len(summary) else 1.0
ax2.set_ylim(0, max(0.1, ymax) * 1.1)
ax2.set_title("조정 결정계수(Adj.R²) 비교")
st.pyplot(fig2)

with st.expander("회귀 상세 결과 보기"):
    for k, m in models.items():
        st.markdown(f"**{k}**")
        st.text(m.summary())

st.markdown("""
### 해석
- 모델1: 2020 GERD → 2023 GDP 기초 선형 회귀
- 모델2: 혼란변수(GDP per Capita, Labor Force Size) 통제 포함
- 모델3: 매개변수(특허, 연구인력 등) 추가
- 모델4: 조절변수(정부/기업 BERD) 상호작용 모형
""")