# -*- coding: utf-8 -*-
"""acdt_g31

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F5fm0D95_3CLMpKv3LVVCJCWz4Vwmcv_
"""

# ================================================================
# 📊 ACDT Group 31 Final Streamlit App
# ================================================================
# - Loads dataset (ACDT_final_dataset.csv) directly from repository
# - Cleans and preprocesses data
# - Performs correlation and multiple regression analysis
# - Provides data visualization and model summary
# ================================================================

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.formula.api as smf

# ================================================================
# 1️⃣ Data Loading & Preprocessing
# ================================================================

@st.cache_data
def load_and_preprocess_data():
    """
    Loads and cleans the dataset (ACDT_final_dataset.csv).
    - Removes non-numeric characters
    - Converts to numeric where possible
    - Drops invalid rows and headers
    """
    try:
        df = pd.read_csv("ACDT_final_dataset.csv", encoding="utf-8-sig")

        # Clean numeric columns (except the first one)
        for col in df.columns[1:]:
            df.loc[2:, col] = (
                df.loc[2:, col]
                .astype(str)
                .str.replace("[^0-9.-]", "", regex=True)
            )
            df.loc[2:, col] = pd.to_numeric(df.loc[2:, col], errors="coerce")

        # Drop first two header rows
        df = df.iloc[2:].copy()

        # Drop rows with NaNs in numeric columns
        numeric_cols = df.columns[1:]
        df.dropna(subset=numeric_cols, inplace=True)

        return df

    except FileNotFoundError:
        st.error("❌ File 'ACDT_final_dataset.csv' not found. Please ensure it's in the repo root.")
        return pd.DataFrame()
    except Exception as e:
        st.error(f"❌ Error loading dataset: {e}")
        return pd.DataFrame()

# ================================================================
# 2️⃣ Streamlit Layout
# ================================================================

st.set_page_config(page_title="ACDT Group 31 Dashboard", layout="wide")
st.title("📈 GERD and Real GDP Analysis (ACDT Group 31)")
st.markdown("""
This interactive dashboard performs:
- Data cleaning and preprocessing
- Correlation and multiple regression analysis
- Visualization of key relationships
---
""")

# ================================================================
# 3️⃣ Load and Preview Data
# ================================================================

df_cleaned = load_and_preprocess_data()

if not df_cleaned.empty:
    st.success("✅ Dataset successfully loaded and preprocessed!")

    st.subheader("📋 Preview of Cleaned Data")
    st.dataframe(df_cleaned.head())

    # ================================================================
    # 4️⃣ Descriptive Statistics
    # ================================================================
    st.header("📊 Descriptive Statistics")
    st.write(df_cleaned.describe())

    # ================================================================
    # 5️⃣ Correlation Heatmap
    # ================================================================
    st.header("📈 Correlation Heatmap")
    corr = df_cleaned.select_dtypes(include=np.number).corr()
    fig, ax = plt.subplots(figsize=(10, 6))
    sns.heatmap(corr, annot=True, cmap="coolwarm", ax=ax)
    st.pyplot(fig)

    # ================================================================
    # 6️⃣ Multiple Linear Regression
    # ================================================================
    st.header("🧮 Multiple Linear Regression")

    numeric_cols = df_cleaned.select_dtypes(include=np.number).columns.tolist()
    dependent_var = st.selectbox("Select dependent variable (Y)", numeric_cols)
    independent_vars = st.multiselect("Select independent variables (X)", numeric_cols)

    if dependent_var and independent_vars:
        formula = f"{dependent_var} ~ {' + '.join(independent_vars)}"
        st.markdown(f"**Regression Formula:** `{formula}`")

        try:
            model = smf.ols(formula=formula, data=df_cleaned).fit()
            st.subheader("📘 Regression Summary")
            st.text(model.summary())

            # ================================================================
            # 7️⃣ Visualization of Key Relationship
            # ================================================================
            first_x = independent_vars[0]
            st.subheader(f"📉 Relationship between {dependent_var} and {first_x}")
            fig2, ax2 = plt.subplots()
            sns.regplot(x=first_x, y=dependent_var, data=df_cleaned, ax=ax2)
            st.pyplot(fig2)

        except Exception as e:
            st.error(f"❌ Regression failed: {e}")

else:
    st.error("⚠️ Dataset could not be loaded. Please check file name or encoding.")