# -*- coding: utf-8 -*-
"""acdt_g31

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F5fm0D95_3CLMpKv3LVVCJCWz4Vwmcv_
"""

# ============================================
# ACDT G31 – GERD(2020) → GDP(2023)
# Full Regressions (Model 1–4) + Viz + Summary
# - CSV: 0행=Year, 1행=Indicator, 2행~ 데이터
# - 한 열 CSV(텍스트)도 안전 분할 (절대 Series를 조건에 쓰지 않음)
# - 숫자 정제는 Series 전용 .str 사용
# - (Indicator, Year) 중복열은 평균으로 통합
# ============================================

import streamlit as st
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import statsmodels.formula.api as smf

st.set_page_config(page_title="ACDT G31 – GERD(2020) → GDP(2023)", layout="wide")

DATA_FILE = "ACDT_final_dataset.csv"  # 앱과 같은 폴더

# ----- 데이터셋의 정확한 라벨 (CSV 헤더와 100% 일치해야 함) -----
GDP_NAME  = "Real GDP (billion USD, PPP-based, Chain-weighted, 2020 base year)"
GERD_NAME = "Gross Domestic Expenditure on R&D (GERD) (current PPP USD)"

MEDIATOR_NAMES = [
    "Resident Patent Applications",
    "Non-Resident Patent Applications",
    "R&D Researchers per Million People",
    "High-tech Export Share (% of Manufactured Exports)",
    "Business R&D Personnel (FTE)",
]
CONFOUNDER_NAMES = ["GDP per Capita", "Labor Force Size"]
MODERATOR_NAMES  = ["Government-financed BERD (%)", "Business-financed BERD (%)"]

X_YEAR = 2020       # GERD는 2020년
Y_YEAR = 2023       # GDP 및 나머지 변수는 2023년 (요구사항 반영)

# ---------- 안전 CSV 파서 (Series truth 방지) ----------
def read_as_multiindex(path: str) -> pd.DataFrame:
    """CSV → 0행=Year, 1행=Indicator, MultiIndex columns.
       - 한 열 CSV도 문자열만으로 분리자 감지/분할 (Series를 if에 절대 사용 안함)
       - 숫자 정제는 Series에서만 .str 사용
       - 중복 (Indicator,Year)은 평균으로 통합
    """
    raw, last_err = None, None
    for enc in ("utf-8-sig", "cp949"):
        try:
            raw = pd.read_csv(path, header=None, encoding=enc, engine="python")
            break
        except Exception as e:
            last_err = e
    if raw is None:
        raise RuntimeError(f"CSV read failed: {last_err}")

    # 한 열 CSV 처리: 샘플 문자열 하나로만 분리자 탐지 (Series를 조건에 쓰지 않음)
    if int(raw.shape[1]) == 1:
        try:
            n = int(min(5, len(raw)))
            sample_text = "\n".join(raw.iloc[:n, 0].astype(str).tolist())
            # 문자열 find() 사용 (불리언 모호성 완전 회피)
            seps = [",", "\t", ";"]
            found_sep = None
            for s in seps:
                if sample_text.find(s) != -1:
                    found_sep = s
                    break
            if found_sep is not None:
                s = raw.iloc[:, 0].astype(str)          # 반드시 Series
                raw = s.str.split(found_sep, expand=True)
        except Exception:
            # 실패 시 원본 유지
            pass

    # 0행=연도, 1행=지표명
    years = raw.iloc[0].astype(str).str.strip().values
    names = raw.iloc[1].astype(str).str.strip().values
    df = raw.iloc[2:].copy()

    # MultiIndex columns
    df.columns = pd.MultiIndex.from_arrays([names, years], names=["Indicator", "Year"])

    # 숫자 정제(Series 전용 .str)
    def clean_series(s: pd.Series) -> pd.Series:
        s = s.astype(str)
        s = s.str.replace(",", "", regex=False)
        s = s.str.replace(r"[^0-9eE+\-\.]", "", regex=True)
        return pd.to_numeric(s, errors="coerce")

    for j in range(df.shape[1]):
        df.iloc[:, j] = clean_series(df.iloc[:, j])

    # Year를 정수로 바꿀 수 있으면 변환
    try:
        new_cols = []
        for ind, yr in df.columns:
            ystr = str(yr)
            if ystr.replace(".", "", 1).isdigit():
                yv = int(float(ystr))
            else:
                yv = yr
            new_cols.append((ind, yv))
        df.columns = pd.MultiIndex.from_tuples(new_cols, names=["Indicator", "Year"])
    except Exception:
        pass

    # (Indicator, Year) 중복열 → 평균 통합
    if bool(df.columns.duplicated(keep=False).any()):
        df = df.T.groupby(level=["Indicator", "Year"]).mean(numeric_only=True).T

    df.index = pd.RangeIndex(len(df))
    return df


def s_at(df_mi: pd.DataFrame, name: str, year) -> pd.Series:
    """(Indicator=name, Year=year) Series 안전 추출. 없으면 NaN Series 반환."""
    lvl0 = df_mi.columns.get_level_values(0)
    if name in set(lvl0):
        sub = df_mi.loc[:, name]  # (행 x Year)
        if year in set(sub.columns):
            return df_mi.loc[:, (name, year)]
    return pd.Series([np.nan] * len(df_mi), index=df_mi.index)


def build_pair_dataset(df_mi: pd.DataFrame, x_year: int, y_year: int) -> pd.DataFrame:
    """GERD(x_year) → GDP(y_year), 그 외 모든 변수(y_year)에 맞춰 구성 + 로그 변환."""
    out = pd.DataFrame(index=df_mi.index)
    out["GERD"] = s_at(df_mi, GERD_NAME, x_year)   # 2020
    out["GDP"]  = s_at(df_mi, GDP_NAME,  y_year)   # 2023

    # 나머지 변수는 모두 y_year(=2023)
    for v in CONFOUNDER_NAMES + MEDIATOR_NAMES + MODERATOR_NAMES:
        out[v] = s_at(df_mi, v, y_year)

    # 로그 변환: 0 → NaN
    out["ln_X"] = np.log(out["GERD"].replace({0: np.nan}))
    out["ln_Y"] = np.log(out["GDP"].replace({0: np.nan}))
    return out.dropna(subset=["ln_X", "ln_Y"]).reset_index(drop=True)


def run_models(df_reg: pd.DataFrame):
    """Model1~4 실행 + 비교표."""
    confs = [c for c in CONFOUNDER_NAMES if c in df_reg.columns]
    meds  = [m for m in MEDIATOR_NAMES  if m in df_reg.columns]
    mods  = [m for m in MODERATOR_NAMES if m in df_reg.columns]

    # M1
    m1 = smf.ols("ln_Y ~ ln_X", data=df_reg).fit()

    # M2
    rhs2 = "ln_X" + ((" + " + " + ".join([f'Q(\"{c}\")' for c in confs])) if len(confs) > 0 else "")
    m2 = smf.ols(f"ln_Y ~ {rhs2}", data=df_reg).fit()

    # M3
    rhs3 = rhs2 + ((" + " + " + ".join([f'Q(\"{m}\")' for m in meds])) if len(meds) > 0 else "")
    m3 = smf.ols(f"ln_Y ~ {rhs3}", data=df_reg).fit()

    # M4 (interaction)
    inter = " + ".join([f'ln_X * Q(\"{mo}\")' for mo in mods]) if len(mods) > 0 else ""
    rhs4 = rhs3 if len(inter) == 0 else f"{rhs3} + {inter}"
    m4 = smf.ols(f"ln_Y ~ {rhs4}", data=df_reg).fit()

    def pick(mod, key="ln_X"):
        return mod.params.get(key, np.nan), mod.pvalues.get(key, np.nan), mod.rsquared_adj

    rows = []
    for label, mod in [("M1: lnY~lnX", m1), ("M2:+conf", m2), ("M3:+med", m3), ("M4:+mods", m4)]:
        beta, pval, adjr2 = pick(mod, "ln_X")
        rows.append([label, beta, pval, adjr2])

    summary = pd.DataFrame(rows, columns=["Model", "β(ln_X)", "p(ln_X)", "Adj.R²"]).round(4)
    return {"M1": m1, "M2": m2, "M3": m3, "M4": m4}, summary


# ----------------- 앱 본문 -----------------
st.title("📈 GERD(2020) → GDP(2023) – Full Regressions (Model 1–4)")

# 디버그용 간단 정보(필요 시 주석 해제)
# st.caption(f"Expecting X=GERD({X_YEAR}), Y=GDP({Y_YEAR}) and all others at {Y_YEAR}")

try:
    df_mi = read_as_multiindex(DATA_FILE)
except Exception as e:
    st.error(f"Error loading data: {e}")
    st.stop()

st.success("✅ Dataset loaded & cleaned (Row0=Year / Row1=Indicator).")

# 분포/상관 (Colab 스타일 요약)
st.header("📊 Distributions & Correlations")
flat = df_mi.copy()
flat.columns = [f"{a} [{b}]" for a, b in flat.columns]
num_only = flat.select_dtypes(include=np.number)

if bool(num_only.empty) is False:
    st.write(num_only.describe().T)
    try:
        fig_corr, ax_corr = plt.subplots(figsize=(12, 7))
        sns.heatmap(num_only.corr(), cmap="coolwarm", center=0, ax=ax_corr)
        ax_corr.set_title("Correlation Heatmap")
        st.pyplot(fig_corr)
    except Exception:
        st.info("Correlation heatmap skipped.")

# 고정 페어: GERD(2020) → GDP(2023)
st.markdown("---")
st.header(f"🧮 Pair: GERD({X_YEAR}) → GDP({Y_YEAR}) (All others at {Y_YEAR})")

df_reg = build_pair_dataset(df_mi, X_YEAR, Y_YEAR)
if df_reg.empty:
    st.warning("No valid observations for this pair after cleaning (ln_X/ln_Y). Check labels/years.")
    st.stop()

st.subheader("📋 Regression dataset (preview)")
st.dataframe(df_reg.head())

# 산점도 + 회귀선 (Colab 시각화 유지)
st.subheader("📉 ln(GERD) vs ln(GDP)")
fig_sc, ax_sc = plt.subplots(figsize=(7, 5))
sns.regplot(x="ln_X", y="ln_Y", data=df_reg, scatter_kws={"alpha": 0.6}, ax=ax_sc)
ax_sc.set_xlabel(f"ln GERD ({X_YEAR})")
ax_sc.set_ylabel(f"ln GDP ({Y_YEAR})")
st.pyplot(fig_sc)

# Model 1–4
models, table = run_models(df_reg)
st.subheader("📘 Model Comparison")
st.dataframe(table)

fig_r2, ax_r2 = plt.subplots(figsize=(6, 4))
sns.barplot(x="Model", y="Adj.R²", data=table, ax=ax_r2)
ymax = float(table["Adj.R²"].max()) if len(table) else 1.0
ax_r2.set_ylim(0, max(0.1, ymax) * 1.1)
ax_r2.set_title("Adjusted R² across models")
st.pyplot(fig_r2)

with st.expander("Full regression summaries"):
    for k, m in models.items():
        st.markdown(f"**{k}**")
        st.text(m.summary())

# 해석 (Colab 설명 반영)
st.markdown("""
### 🧩 Interpretation (2020→2023)
- **Model 1**: lnGERD(2020) → lnGDP(2023) 기본 탄력성.
- **Model 2**: GDP per Capita, Labor Force(2023) 통제로 **혼란효과** 점검(lnGERD 계수 변화 확인).
- **Model 3**: 특허·연구인력·하이테크수출·기업R&D인력(2023) 포함 → lnGERD 계수 감소/유의성 변화 시 **매개효과** 시사.
- **Model 4**: Government/Business-financed BERD(2023) 상호작용 p<0.05면 **조절효과** 유의.
""")